import { InitialState, Item } from "./types/types";
const image =
  "https://storage.googleapis.com/download/storage/v1/b/task-tracker-336811.appspot.com/o/%2Fusers%2Fimgs%2Fuser-61d5e487b45306781f0cea46-1642267623054.jpeg?generation=1642267623313359&alt=media";

const stock = [
  {
    _id: "1",
    image,
    name: "pencilsuui",
    buyingCurrency: "usd",
    sellingCurrency: "ksh",
    buyingPrice: "900",
    sellingPrice: "300",
    description: "the latest chinese brabd",
    stock: 2,
    supplier: "mayadnja",
    isReturnable: true,
    packaging: "one",
    category: "stationery",
  },
  {
    _id: "2",
    name: "books",
    buyingCurrency: "ugx",
    sellingCurrency: "ugx",
    sellingPrice: "300",
    image: undefined,
    description: "the latest chinese brabd",
    stock: 10,
    buyingPrice: "9200",
    isReturnable: false,
    packaging: "dozens",
    supplier: "mayansssja",
    category: "books",
  },
  {
    _id: "3",
    name: "chalk",
    supplier: "mayssanja",
    buyingCurrency: "ugx",
    sellingCurrency: "usd",
    sellingPrice: "30090",
    buyingPrice: "90",
    description: "new stock",
    stock: 10000,
    isReturnable: false,
    image,
    packaging: "box",
    category: "food",
  },
  {
    _id: "4",
    name: "chalkie",
    buyingCurrency: "ksh",
    sellingCurrency: "ugx",
    description: "new stock",
    stock: 10000,
    buyingPrice: "2900",
    isReturnable: false,
    sellingPrice: "12000",
    packaging: "box",
    category: "groceries",
    supplier: "mayanjadjk",
    image: undefined,
  },
  {
    _id: "5",
    name: "chalked",
    buyingCurrency: "ugx",
    sellingCurrency: "ksh",
    sellingPrice: "300",

    buyingPrice: "9002",
    description: "new stock",
    stock: 10000,
    supplier: "mayanjall",
    isReturnable: true,
    packaging: "box",
    category: "stationery",
    image: undefined,
  },
  {
    _id: "6",
    name: "chalk",
    buyingCurrency: "ugx",
    sellingCurrency: "usd",

    supplier: "mayaeenja",
    description: "new stock",
    stock: 10000,
    buyingPrice: " 3900",
    sellingPrice: "12000",
    isReturnable: true,
    packaging: "box",
    category: "food",
    image: undefined,
  },
  {
    _id: "7",
    name: "chalker",
    buyingCurrency: "ugx",
    sellingCurrency: "ugx",
    description: "new stock",
    stock: 10000,
    sellingPrice: "12000",
    isReturnable: false,
    packaging: "box",
    buyingPrice: "9400",
    category: "stationery",
    supplier: "mayanja",
    image: undefined,
  },
  {
    _id: "8",
    name: "tv",
    buyingCurrency: "ugx",
    sellingCurrency: "ugx",
    buyingPrice: "3900",
    description: "new stock",
    stock: 19000,
    sellingPrice: 12000,
    isReturnable: true,
    packaging: "box",
    category: "groceries",
    supplier: "bafra",
    image: undefined,
  },
  {
    _id: "9",
    name: "face",
    buyingCurrency: "ugx",
    sellingCurrency: "ugx",
    sellingPrice: "300",
    buyingPrice: "900",
    description: "new stock",
    stock: 1300,
    isReturnable: false,
    packaging: "box",
    category: "food",
    supplier: "mayanja",
    //  image:"",
  },
];
const initialValues: Item = {
  _id: "",
  name: "",
  description: "",
  category: "",
  isReturnable: false,
  stock: '0',
  buyingPrice: "0",
  sellingPrice: "0",
  image: "",
  supplier: "",
  buyingCurrency: "ugx",
  sellingCurrency: "ugx",
  packaging: "",
};

const categories: InitialState["categories"] = [
  { title: "Choose Category  *", value: "", _id: "0" },
  { title: "food", value: "food", _id: "09" },
  { title: "groceries", value: "groceries", _id: "80" },
  { title: "stationery", value: "stationery", _id: "090" },
  
];
const store: Array<Item> = stock;
const categoriesStore = categories;
const initialState: InitialState = {
  availableStock: store,
  loading: false,
  cart: [],
  initialValues,
  displaySearchBar: store.length === 0 ? false : true,
  displayCategoriesSearchBar: categoriesStore.length === 0 ? false : true,
  infoMsg: "",
  categories: categoriesStore,
  isEditing: false,
  editable: "",
};

export { store, initialValues, categoriesStore, initialState };
