module.exports = {
  up: (queryInterface, Sequelize) => {
    return queryInterface.bulkInsert("Items", [
      {
        name: "craksy,dons",
        buyingPrice: 80,
        sellingPrice: 100,
        buyingCurrency: "ugx",
        packaging: "each",
        user: "fbalimuttajjo@gmail.com",
        category: "pps",
        description: "this is after ",
        sellingCurrency: "usd",
        stock: 12,
        supplier: "bamayanja investments",
        isReturnable: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "pusksie",
        buyingPrice: 80,
        sellingPrice: 100,
        buyingCurrency: "usd",
        user: "fbalimuttajjo@gmail.com",
        packaging: "dozens",
        category: "food",
        description: "this is after ",
        sellingCurrency: "usd",
        stock: 12,
        supplier: "bamayanja investments",
        isReturnable: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "crakydonks",
        buyingPrice: 80,
        sellingPrice: 100,
        buyingCurrency: "ugx",
        packaging: "each",
        category: "pps",
        user: "bamayanja@gmail.com",
        description: "this is after ",
        sellingCurrency: "usd",
        stock: 12,
        supplier: "bamayanja investments",
        isReturnable: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "pusike",
        buyingPrice: 80,
        sellingPrice: 100,
        buyingCurrency: "usd",
        user: "bamayanja@gmail.com",
        packaging: "dozens",
        category: "food",
        description: "this is after ",
        sellingCurrency: "usd",
        stock: 12,
        supplier: "bamayanja investments",
        isReturnable: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ]);
  },
  down: (queryInterface, Sequelize) => {
    return queryInterface.bulkDelete("Items", null, {});
  },
};
